name: Build Bisq

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macOS-latest, windows-latest]
            java: [ '11', '11.0.3', '15', '15.0.5']
    name: Test Java ${{ matrix.Java }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        lfs: true

    - name: Set up JDK
      uses: actions/setup-java@d854b6da19cdadd9a010605529e522c2393ebd38
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Validate Gradle Wrapper JAR files
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build with Gradle
      run: ./gradlew build

    - name: Print Dependency Verification Report
      if: ${{ failure() }}
      run: cat build/reports/dependency-verification/*/*.html
      shell: bash
